### ISSUE TITLE
这个已经稳定了吗？能在生产环境上使用吗？

### ISSUE THREAD

**Issue by maiqingqiang** [AgoraIO-Community/AgoraWebSDK-NG#1]
这个已经稳定了吗？能在生产环境上使用吗？

**Comment by disoul** [comment]
等我们在这里发布第一个 Relaease 版本后可以在生产环境上使用，但是我们不保证 API 稳定，在替代官网版本之前，我们会先以 Beta Program 的方式在这里发版收集一段时间用户们的意见，在这段时间内可能会对 API 和功能做一些修改。

> 我们最近正在给 Agora Web SDK NG 做发版前最后的准备，预计本周内会在仓库里发布第一个 Release 版本（v0.1.0）

**Comment by maiqingqiang** [comment]
这个也是属于声网官方维护的吗？

**Comment by maiqingqiang** [comment]
> 等我们在这里发布第一个 Relaease 版本后可以在生产环境上使用，但是我们不保证 API 稳定，在替代官网版本之前，我们会先以 Beta Program 的方式在这里发版收集一段时间用户们的意见，在这段时间内可能会对 API 和功能做一些修改。
> 
> > 我们最近正在给 Agora Web SDK NG 做发版前最后的准备，预计本周内会在仓库里发布第一个 Release 版本（v0.1.0）

这个也是属于声网官方维护的吗？

**Comment by disoul** [comment]
是的，都是由 Agora WebRTC 团队官方维护

**Comment by maiqingqiang** [comment]
期待早日Relaease  这个文档比以前的文档好很多了

**Comment by jinyeqing** [comment]
@maiqingqiang  已经更新上线，可以体验反馈啦～欢迎来找茬哈哈

**Comment by maiqingqiang** [comment]
> @maiqingqiang 已经更新上线，可以体验反馈啦～欢迎来找茬哈哈

好  准备迁移更新到AgoraWebSDK-NG体验一下

**Comment by jinyeqing** [comment]
@maiqingqiang 
我们下周准备组织一个交流活动，邀请一些开发者和我们NG版本的研发一起，后续大家有NG版本问题也可以及时交流，你如果愿意参与可以发你的微信或者手机到邮箱：jinyeqing@agora.io

**Comment by jinyeqing** [comment]
@maiqingqiang  我们下周准备组织一个交流活动，定向邀请开发者来参与体验，然后根据咱们的反馈进行更多的功能和体验完善。后续大家有NG版本问题也可以及时交流，欢迎来体验交流～～你如果愿意参与可以发你的微信回复给我邮箱： jinyeqing@agora.io
