### ISSUE TITLE
Console logging in Production

### ISSUE THREAD

**Issue by gibsonsyd** [AgoraIO-Community/AgoraWebSDK-NG#10]
![Screenshot 2020-05-19 at 22 16 57](https://user-images.githubusercontent.com/9051764/82373918-9d7af980-9a1e-11ea-8fa8-8e91d2383a99.png)

Hi, is there any way to remove console logging from your SDK in production env? See screenshot.

Thanks
P

**Comment by disoul** [comment]
1. call [AgoraRTC.setLogLevel(4)](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#setloglevel) to stop the log output. 
2. call `console.clear()` to clear your console.
