### ISSUE TITLE
Bad Screenshare Quality

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#103]
### Describe the bug
When a person screenshares, we see frequent glitches on some windows computers where the entire screenshare or parts of the screenshare completely grey out. This happens only on Windows laptops and only on some windows laptops. Across different channels its the same windows laptops that face the issue again and again. 

MODE: 'live'
CODEC: 'h264'
SDK Version 4.0.1.

### SDK Logs
> You should call [enableLogUpload](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#enablelogupload) to enable log upload to Agora's Log Server.

**Channel**:    
Channel: APP5628

**UID**:    
UID of Host Streaming Screenshare: 
Video Stream: 748093
Screenshare Stream: 748092

UID of viewers who faced issues: 
Viewer 1: 748108
Viewer 2: 748071, 748073, 748074

UID of viewers without issues: 
Viewer 3:748101, 748103, 748104
Viewer 4: 748098
Viewer 5: 748143

All of the above are windows computers. 2 of the 5 viewers faced issues.

Please take a look at this video from 2:06 onwards: https://drive.google.com/file/d/1fRS3wLlaDXS-ZywS2fGel5E9Agbr3nFj/view?usp=sharing

**Comment by HAHAHA44** [comment]
If there are no Native user, you`d better use vp8 codec.
