### ISSUE TITLE
AgoraRTCError INVALID_OPERATION: Can't publish stream, no join info!

### ISSUE THREAD

**Issue by FarazPatankar** [AgoraIO-Community/AgoraWebSDK-NG#105]
### Describe the bug
We've had this issue pop up on Sentry a few times now. Here's what we see on our end:
```
{
code: INVALID_OPERATION, 
data: [undefined], 
message: AgoraRTCError INVALID_OPERATION: Can't publish stream, no join info!, 
name: AgoraRTCException
}
```

Here's the code we've written for publishing the streams:
```
const tracks = await createLocalTracks()

await client.join(appId, String(channel), token, uid)
await client.enableDualStream()
await client.setStreamFallbackOption(remoteUserVideoUid, 2)
await client.publish(tracks)
```

Could someone shed some light on why this happens and how we can avoid it? Would adding a simple check like this help?
```
if (client.connectionState === 'CONNECTED') {
  await client.publish(tracks)
}
```

And can we be sure that this code will actually run once the client is connected after a disconnection/reconnection?

Any help would be greatly appreciated!

**Comment by rohanJa** [comment]
put uid =0 see if that works

**Comment by HAHAHA44** [comment]
It is because you call publish before join. The above simple code is useful( check the connectionState before publish).
