### ISSUE TITLE
AgoraRTCError INVALID_OPERATION: Dual stream is already enabled

### ISSUE THREAD

**Issue by FarazPatankar** [AgoraIO-Community/AgoraWebSDK-NG#107]
### Describe the bug
We've had this issue pop up on Sentry a few times now. Here's what we see on our end:
```
{
code: INVALID_OPERATION, 
data: [undefined], 
message: AgoraRTCError INVALID_OPERATION: Dual stream is already enabled, 
name: AgoraRTCException
}
```

Here's the code we've written for publishing the streams:
```
const tracks = await createLocalTracks()

await client.join(appId, String(channel), token, uid)
await client.enableDualStream()
await client.setStreamFallbackOption(remoteUserVideoUid, 2)
await client.publish(tracks)
```

Could someone shed some light on why this happens and how we can avoid it? Is there a way to check if the dual-stream is already enabled and not re-enable it?

Any help would be greatly appreciated!

**Comment by FarazPatankar** [comment]
@HAHAHA44 @disoul it has been more than a month since I posted this issue and we still face it daily. Any thoughts on this?

**Comment by HAHAHA44** [comment]
The SDK has not yet provided an external interface to inform the user whether the dual stream have been enabled. You can maintain a state by yourself to know whether you have opened dual stream. If you called enableDualStream without error, set state to true.

If you still want to get relevant information from the client for the dual stream anyway, you can use the private parameter client._isDualStreamEnabled.

**Comment by FarazPatankar** [comment]
So what I ended up doing was silently ignoring the error in case it was already enabled as I don't really want to do anything else in that case anyway. Is that okay as well?

**Comment by HAHAHA44** [comment]
Yes you can ignore the error. Just try catch and do nothing.
 But it maybe a warning that the logic of using SDK has some problems.
