### ISSUE TITLE
Type problems withn ILocalTrack when trying to publish/unpublish local tracks

### ISSUE THREAD

**Issue by Vennufius** [AgoraIO-Community/AgoraWebSDK-NG#111]
I am using Vue 3 and I created an interface for RTC which includes localAudioTrack: ILocalAudioTrack and localVideoTrack: ILocalVideoTrack and other stuff not relevant here. After creating the tracks I would like to publish the tracks but the publish gives me the following error:

Type '{ setVolume: (volume: number) => void; getVolumeLevel: () => number; setAudioFrameCallback: (audioFrameCallback: ((buffer: AudioBuffer) => void) | null, frameSize?: number | undefined) => void; ... 15 more ...; removeAllListeners: (event?: string | undefined) => void; }' is missing the following properties from type 'ILocalTrack': _events, _indexOfListenerts(2739)

Platform and Browser:
Web, Chrome    

SDK Version:
Latest

Steps to reproduce:
Initialise client normally and then the following:
`rtc.localAudioTrack = await AgoraRTC.createMicrophoneAudioTrack();  
rtc.localVideoTrack = await AgoraRTC.createCameraVideoTrack();  
await client.publish([rtc.localAudioTrack, rtc.localVideoTrack]);
`
rtc is a reactive from Vue which implements the RTC inteface.

**Comment by AgoraWebAnZhaowei** [comment]
## No exception:

@Vennufius :

I wrote a demo according to your description and **everything works fine**.

Vue version that I installed is **3.0.3**.

These are the codes I wrote in the script tag of my component：
```js
import AgoraRTC from "agora-rtc-sdk-ng";

export default {
  name: "HelloWorld",
  data() {
    return {
      client: null,
      rtc: {
        localAudioTrack: null,
        localVideoTrack: null
      }
    };
  },
  mounted: async function() {
    const client = AgoraRTC.createClient({ mode: "rtc", codec: "vp8" });
    this.subscribe(client);
    await client.join(
      "/**your app id*/",
      "/**your channel name**/",
      null
    );
    this.client = client;
    this.rtc.localAudioTrack = await AgoraRTC.createMicrophoneAudioTrack();
    this.rtc.localVideoTrack = await AgoraRTC.createCameraVideoTrack();
    await client.publish([this.rtc.localAudioTrack, this.rtc.localVideoTrack]);
  },
  methods: {
    subscribe(client) {
      client.on("user-published", async (user, mediaType) => {
        await client.subscribe(user, mediaType);
        console.log("-----subscribe success");
        if (mediaType === "video") {
          const remoteVideoTrack = user.videoTrack;
          const playerContainer = document.createElement("div");
          playerContainer.id = user.uid.toString();
          playerContainer.style.width = "640px";
          playerContainer.style.height = "480px";
          document.body.append(playerContainer);

          remoteVideoTrack.play(playerContainer);
        }
        if (mediaType === "audio") {
          const remoteAudioTrack = user.audioTrack;
          remoteAudioTrack.play();
        }
      });
    }
  }
};
```

**Comment by Vennufius** [comment]
Yes, but I wrote it using the composition api of Vue 3, which didn't work. As I said "rtc is a reactive from Vue...".

Also the problem I'm having is related to TypeScript and you are using the JavaScript version.  I'm currently using it with the JS version since that works, but it would be nice to get it to work with TS as well.

**Comment by AgoraWebAnZhaowei** [comment]
There are declares of ILocalAudioTrack and ILocalVideoTrack in `node_modules/agora-rtc-sdk-ng/rtc-sdk_en.d.ts`.
Is the declaration of the tracks you use in this file?

**Comment by Vennufius** [comment]
Yes they are the ones provided by Agora. I tried both ILocalTrack and ILocalAudioTrack and ILocalVideoTrack, also ICameraVideoTrack and IMicrophoneAudioTrack (all provided by the agora library), but neither worked after assigning it to vue composition api reactive. If I assign it to a normal variable it works, the disconnect is when I assign it to a vue reactive, it seems to drop some needed property types.

**Comment by AgoraWebAnZhaowei** [comment]
Yes,I reproduced it, I got the same error. 
And maybe you can do this:

I wrote it by typescript and everything works fine.
```typescript
interface RtcI {
  localAudioTrack: ILocalAudioTrack;
  localVideoTrack: ILocalVideoTrack;
}
const rtc: RtcI = {
        localAudioTrack: audioTrack,
        localVideoTrack: videoTrack
      };
const reactiveRtc = reactive(rtc) as IRtc;  // from Vue 3 Docs
await client.publish([
        reactiveRtc.localAudioTrack,
        reactiveRtc.localVideoTrack
      ]);
```
This will help you:
[Vue 3 Doc about Typescript typing-reactive](https://github.com/vuejs/docs-next/blob/80ddbb77178005bddf8f1e1af5623bca4abeaba6/src/guide/typescript-support.md#typing-reactive)

**Comment by Vennufius** [comment]
Ok weird. So this works, but the docs also say that creating the interface with:
```typescript
```

**Comment by Vennufius** [comment]
Ok weird, so this works, but when creating the reactive the other way:
```typescript
const const rtc = reactive<RtcI>(rtc);
```
does not work, even though it seems to be a valid way in the Vue docs. Am I missing something or why do these behave diffrerently?

Thank you anyway! This other way of defining seemed to do the trick

**Comment by AgoraWebAnZhaowei** [comment]
Yes, I tried all the methods in the Vue document, only As works.
 I guess it is a defect in Typescript's type inference mechanism after proxy.
