### ISSUE TITLE
Question: how to catch if a screenshare is stopped using the browser's Stop button?

### ISSUE THREAD

**Issue by pgib** [AgoraIO-Community/AgoraWebSDK-NG#112]
### Describe the bug

When there's an active screen share, the browser (Chrome in my case) adds a banner to the top of all windows that informs the user that screen content is being shared. If I use the browser's Stop button, it's unclear how I detect that using the Agora SDK. It currently leaves the stream playing, but it's a black box.

![image](https://user-images.githubusercontent.com/13967/100478596-89384900-30a0-11eb-9e87-dd1b3b980ba9.png)

**Comment by HAHAHA44** [comment]
Thank you for your feedback. It is a very useful feature to know that screen sharing is turned off. We will add this feature in subsequent versions

**Comment by FarazPatankar** [comment]
Hey @pgib, we ran into this issue too, there's an event you can listen to and then handle it. Here's how we do it. 

```localScreenTrack.on('track-ended', handleStopScreenShare)```

**Comment by pgib** [comment]
> Hey @pgib, we ran into this issue too, there's an event you can listen to and then handle it. Here's how we do it.
> 
> `localScreenTrack.on('track-ended', handleStopScreenShare)`

@FarazPatankar Thanks, that's perfect! 💯
