### ISSUE TITLE
Question: How to get IRemoteVideoTrack's dimensions

### ISSUE THREAD

**Issue by matamatanot** [AgoraIO-Community/AgoraWebSDK-NG#113]
### Describe the bug
In console, I found the following
`current video dimensions: 640 480`

Isn't there a function like `IRemoteVideoTrack.getDimensions` ?

**Comment by HAHAHA44** [comment]
There may be the information you want in the method client.getRemoteVideoStats() 
https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartcclient.html#getremotevideostats

**Comment by matamatanot** [comment]
I have been looking for `receiveResolutionHeight` and `receiveResolutionWidth`. Thanks!
