### ISSUE TITLE
Video fails on remote device when localTracks.audioTrack.setEnabled(false)

### ISSUE THREAD

**Issue by lluichi** [AgoraIO-Community/AgoraWebSDK-NG#114]
### Describe the bug
When on a local device we tried to disable the audioTrack with 
localTracks.audioTrack.setEnabled(false)
the remote device stop receiving the audioTrack as expected, but it also stop receiving the videoTrack

### SDK Logs
I'm attaching the remote device Console logs. After stop receiving the remote video, RECV_VIDEO_DECODE_FAILED and  RECV_VIDEO_DECODE_FAILED_RECOVER errors are displayed continuously on the remote device console log, and the remote video is not displayed.

19:00:45:456 Agora-SDK [DEBUG]: [client-acf3f] receive mute message 1429446278 audio true
AgoraRTC_N.js:400 19:00:45:458 Agora-SDK [DEBUG]: [client-acf3f] user-info-update, uid: 1429446278, msg: mute-audio
AgoraRTC_N.js:400 19:00:45:460 Agora-SDK [DEBUG]: [client-acf3f-sub-3] update subscribe options [a: true, v: true] -> [a: false, v: true]
AgoraRTC_N.js:401 19:00:45:464 Agora-SDK [INFO]: [track-track-680b6284] is destroyed
AgoraRTC_N.js:400 19:00:45:468 Agora-SDK [DEBUG]: [track-680b6284] stop audio playback
AgoraRTC_N.js:401 19:00:45:483 Agora-SDK [INFO]: [client-acf3f] remote user 1429446278 unpublished audio
AgoraRTC_N.js:400 19:00:45:506 Agora-SDK [DEBUG]: [track-93525dca] video-element-status change playing => paused
AgoraRTC_N.js:400 19:00:45:508 Agora-SDK [DEBUG]: [track-track-93525dca] video element paused, auto resume
AgoraRTC_N.js:400 19:00:45:644 Agora-SDK [DEBUG]: [track-93525dca] current video dimensions: 640 480
AgoraRTC_N.js:400 19:00:45:646 Agora-SDK [DEBUG]: [track-93525dca] video-element-status change paused => playing
AgoraRTC_N.js:400 19:00:45:651 Agora-SDK [DEBUG]: [track-93525dca] current video dimensions: 640 480
AgoraRTC_N.js:400 19:00:45:909 Agora-SDK [DEBUG]: [track-93525dca] video-element-status change playing => destroyed
AgoraRTC_N.js:400 19:01:07:195 Agora-SDK [DEBUG]: [client-acf3f] receive exception msg, code: 1005, msg: RECV_VIDEO_DECODE_FAILED, uid: 1429446278
AgoraRTC_N.js:400 19:01:12:201 Agora-SDK [DEBUG]: [client-acf3f] receive exception msg, code: 3005, msg: RECV_VIDEO_DECODE_FAILED_RECOVER, uid: 1429446278
AgoraRTC_N.js:400 19:01:22:195 Agora-SDK [DEBUG]: [client-acf3f] receive exception msg, code: 1005, msg: RECV_VIDEO_DECODE_FAILED, uid: 1429446278
AgoraRTC_N.js:400 19:01:27:205 Agora-SDK [DEBUG]: [client-acf3f] receive exception msg, code: 3005, msg: RECV_VIDEO_DECODE_FAILED_RECOVER, uid: 1429446278

**Channel**: vcall20201204   

**UID**: local user 3209144043   

Platform and Browser: Linux and Chrome 86 as local device, Android Xiaomi mobile phone and Chrome 87 as remote device, but this issue happens in all devices we have tried this.

SDK Version:  AgoraRTC_N.js

### To Reproduce
1. Go to 'AgoraWebNG/Demos/basicVideoCall/' deni
2. Open the Chrome console log
3. Execute: 'localTracks.audioTrack.setEnabled(false);'
4. See error in the remote device Console log and that in the remote device, the remote audio has stop correctly, but the video also.
5. Audio can be reenabled with 'localTracks.audioTrack.setEnabled(true);' but the remote video does not recover.

**Comment by HAHAHA44** [comment]
setEnabled(false) will trigger the peer "user-unpublished" event. There is a parameter in the "user-unpublished" event that indicates the type of track that the peer has unpublished. But the function that handles the "user-unpublished" event in our Demo does not judge the track type. As a result, when you setEnabled(false) on the audio track, the video track of the peer will also be removed.
