### ISSUE TITLE
TypeError: Cannot assign to read only property 'process' of object '#<Window>'

### ISSUE THREAD

**Issue by aquezada** [AgoraIO-Community/AgoraWebSDK-NG#115]
Hi, I have a problem, what appears in console is:
TypeError: Cannot assign to read only property 'process' of object '#<Window>'

<img width="1188" alt="Screen Shot 2020-12-09 at 07 48 39" src="https://user-images.githubusercontent.com/18424/101620148-f4fca900-39f2-11eb-93e3-fbaabdb53194.png">

removing "window.process = {env: {DEBUG: void 0}}" from the AgoraRTC_N-production.JS file, it works. How does it affect?

in Create React App. Please help.

SDK Version:    
  "agora-rtc-sdk-ng": "^4.1.1",

**Comment by KenSison** [comment]
I'm getting the same error.
I don't know if it's directly related, but it happened when I updated apollo-client to v3.

**Comment by Dschoordsch** [comment]
> I'm getting the same error.
> I don't know if it's directly related, but it happened when I updated apollo-client to v3.

Same here

**Comment by mkgo** [comment]
I am also getting the same error and it seems to have to do with npm packages and versions.

I have an older .lock file and if I build with that I do not get the error. But with a clean (no lock file build) then I get that error which is coming from AgoraRTC_N-production.js file at line 224.

**Comment by aquezada** [comment]
Resolved in 4.2.1
