### ISSUE TITLE
Large Event Usage

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#116]
Hi,

This is more just a question. We've been using ng-sdk in production for a while and it has been pretty stable. The largest we've used it for is 1800 concurrent users. We have an event coming up this week with 10k concurrent users, is there anything we should be concerned about with ng-sdk?

Best,
Vedha

**Comment by vvedharaju** [comment]
@HAHAHA44 @disoul thoughts?

**Comment by EaSonic** [comment]
Hi @vvedharaju,
Glad to hear you are happy with the ng-sdk, for the scenario you mentioned about 10k concurrent user, I believe in sdk side there should be no problem;
**BUT if you want to expend your usage:**
1. Could you please inform CSDC just in case, we may need to check the capacity depends on when and where your event is.
2. For future large event held, could you please inform CSDC as well in the service side? We developers will check issues here but it is not efficient for us to check capacity in your area before the event is held.
