### ISSUE TITLE
Cannot publish audio track from file without remote users hearing audio track twice

### ISSUE THREAD

**Issue by rohan-suri** [AgoraIO-Community/AgoraWebSDK-NG#119]
### Describe the bug
I would like to publish an audio track from a file such that all users in a channel can hear the audio track including the user publishing the audio track. Here is my code for publishing and playing the audio track:
```
    const audioFileTrack = await AgoraRTC.createBufferSourceAudioTrack({
      source: myFile,
    });
    audioFileTrack.startProcessAudioBuffer();
    audioFileTrack.play();
    await agoraClient.publish(audioFileTrack);
```
The problem is that if the user is not wearing headphones, then the remote users both hear the published audio track twice, once from the published track and second from the user's local audio track feeding into their that person's microphone.

I could force the user to be muted when playing (but I would like people to talk) or I could remove the `audioFileTrack.play()` but then the publishing user does not hear the audio file. Any ideas on how to prevent the local audio track playing from feeding into the microphone?

**Comment by HAHAHA44** [comment]
In browser, only the far-end audio received through the p2p connection will not be collected again when it is played. 

If you want to play local audio and publish local microphone track, you have better to wear headphones.

**Comment by rohan-suri** [comment]
Thanks for the response! That's unfortunate regarding only that p2p connections are not collected again. Do you know if this is a browser setting or a configuration of the Agora sdk?

**Comment by HAHAHA44** [comment]
This is a issue of browser.
https://github.com/webrtc/samples/issues/1243

**Comment by rohan-suri** [comment]
Thank you that link was helpful!
