### ISSUE TITLE
exception 2001 fired for too long

### ISSUE THREAD

**Issue by livefire2015** [AgoraIO-Community/AgoraWebSDK-NG#12]
Problem:
The exception 2001 AUDIO_INPUT_LEVEL_TOO_LOW is shown for 30 seconds before a newly-joined user could be heard by others in the same channel.

Console log:
<img width="994" alt="image" src="https://user-images.githubusercontent.com/11730364/83466440-f3db3580-a42b-11ea-86db-b7dc7aaee605.png">

How to reproduce:
1. Start a video call using the Web SDK NG.
2. Ask ten people to join the call one-by-one.
3. 7 out of 10 people report that they cannot be heard by others during the first 30 seconds since they join.
4. After 30 seconds, the exception 2001 goes away.

**Comment by disoul** [comment]
The `exception` event is not an error, it is just a warning to remind you something in the channel is not working normally. This warning is base on a monitor for WebRTC Stats. If this monitor finds some stats value is abnormal for a long time, it will emit the `exception` event.

In your case, exception 2001 means your input audio level is too low for a long time. It will make other people can not hear you, but SDK can not know what's wrong with your microphone, maybe you should check it by your self or show an alert on the webpage.
