### ISSUE TITLE
Is there a setting to buffer audio instead of dropping packets?

### ISSUE THREAD

**Issue by rohan-suri** [AgoraIO-Community/AgoraWebSDK-NG#120]
Hi, we have one user streaming audio to everyone else in the channel. The problem is some users report the audio is cutting out frequently. We realize this is probably due to poor network signal. 

Is there a setting in Agora that will make audio buffer instead of dropping packets? We are fine if people's audio is delayed a few seconds, but we need to make sure it is smooth. 

Any setting that is okay with high latency but prioritizes smoothness is highly appreciated.

**Comment by yoreland** [comment]
which channel profile you are current using?
if you are using communication profile, your could try to use liveboardcasting profile. And make listeners as audience role.

**Comment by HAHAHA44** [comment]
We will launch a Real-time Live Streaming function in the next version. In the future, audiences can have two gears to adjust the reception delay. This feature may be helpful to you.

There is currently no way for the audience to adjust the buffer.

**Comment by rohan-suri** [comment]
Thank you for the response!
