### ISSUE TITLE
小程序直播视频上麦 web ng sdk收不到video的publish命令

### ISSUE THREAD

**Issue by AdamFu** [AgoraIO-Community/AgoraWebSDK-NG#122]
### Describe the bug
老师使用web ng sdk开始直播，学生使用小程序sdk视频上麦。 web ng sdk只收到了audio的user-published事件，没有收到video的，导致无法看到学生的视频，只能听到声音
### SDK Logs
> You should call [enableLogUpload](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#enablelogupload) to enable log upload to Agora's Log Server.

**Channel**:    
C290
**UID**:    
老师uid：91
学生uid：144101
Platform and Browser:    

SDK Version:    
web ng sdk版本：v4.2.1
小程序版本：v2.4.5
### To Reproduce
1. ng sdk开始直播
2. 学生通过小程序sdk视频上麦
3. ng sdk只收到了audio的user-published事件，没有收到video

**Comment by plutoless** [comment]
@AdamFu 您好，您可以先用一下这个web-ng的特殊版 https://download.agora.io/sdk/web/AgoraRTC_N-4.1.1.100.js
小程序的下个版本会修复这个问题，大概在3月发布
