### ISSUE TITLE
Next.js implementation problem

### ISSUE THREAD

**Issue by cosakin** [AgoraIO-Community/AgoraWebSDK-NG#123]
Hi, i tries to integrate agora in my next.js project but have some problem. The problem is the problem is next.js SSR concept. when i was import standard way
(import AgoraRTC from "agora-rtc-sdk-ng"), i see window not defined.
I tried dynamic import but this time when i was create client and local functions i cannot reach. 
How do i solve this?

SDK Version: 4.3.0

![error](https://user-images.githubusercontent.com/30292080/107860228-3b391300-6e4f-11eb-86ea-23cc53aef15e.png)

```javascript
import React, { useEffect, useState, useRef } from "react"
import Head from "next/head"
import dynamic from "next/dynamic"
import Link from "next/link"
import styles from "../styles/Call.module.css"


const DynamicAgoraComponent = dynamic(
  () => import("agora-rtc-sdk-ng").then((mods) => mods.AgoraComponent),
  {
    ssr: false,
  },
)

function Meeting() {
  const rtc = {
    // For the local client.
    client: null,
    // For the local audio and video tracks.
    localAudioTrack: null,
    localVideoTrack: null,
  }

  const options = {
    // Pass your app ID here.
    appId: "d02c58eeb2a3463f839a6cd216d01ded",
    // Set the channel name.
    channel: "",
    // Pass a token if your project enables the App Certificate.
    token: null,
  }

  async function startBasicCall() {
    rtc.client = AgoraRTC.createClient({ mode: "rtc", codec: "h264" })
    const uid = await rtc.client.join(
      options.appId,
      options.channel,
      options.token,
      null,
    )
    // Create an audio track from the audio sampled by a microphone.
    rtc.localAudioTrack = await AgoraRTC.createMicrophoneAudioTrack()
    // Create a video track from the video captured by a camera.
    rtc.localVideoTrack = await AgoraRTC.createCameraVideoTrack()
    // Publish the local audio and video tracks to the channel.
    await rtc.client.publish([rtc.localAudioTrack, rtc.localVideoTrack])
  }

  startBasicCall()

  console.log("publish success!")

  return (
    <div className={styles.container}>
      <DynamicAgoraComponent />
      <Head>
        <title>Meeting Page | Video Call App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Call Page</h1>
      <p>
        window={window.width} x {window.height}
      </p>
      <br />
      <Link href="/">
        <p>Main Page</p>
      </Link>
    </div>
  )
}

export default Meeting

```

**Comment by cosakin** [comment]
I tried like this. Didn't solve it

![code](https://user-images.githubusercontent.com/30292080/107885071-2456f700-6f09-11eb-87c2-97871169ca54.png)

**Comment by plutoless** [comment]
the sdk is for client use, to import it directly in your ssr project it will lead to issues you mentioned. 
there are multiple approaches to solve this issue but this might give you some hint https://github.com/nuxt/nuxt.js/issues/469

**Comment by flyxii** [comment]
Hi, I encounter the same issue. May I know if there is any proper approach please?

**Comment by cosakin** [comment]
Hi again, sorry for my delay. I solved same issue in Gatsbyjs but even not tried again in Nextjs. I will feedback asap about it.

**Comment by cosakin** [comment]
Hi again:) ,
I solved problem. Agora need window but in NextJS concept doesnt fit that. 

NextJS support [dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import). When you read document, you can see **With no SSR** section. On the other hand Agora package cannot import like this.
The solution is you must design page as a component. After this, you can dynamic import to pages like component. 

I drop repo link i did like this
https://github.com/cosakin/Agora-NoSSR-Solution

Regards.
