### ISSUE TITLE
Webapp Integration 

### ISSUE THREAD

**Issue by neuralAxiom** [AgoraIO-Community/AgoraWebSDK-NG#13]
hey, I am trying to integrate agora into my web app. I want it to be one to one. I am not being able to do it. Third-person can still join in and then the quality drops drastically. Can anyone help me fix it

**Comment by disoul** [comment]
Unfortunately, the Agora Platform does not support setting the maximum number of users in the channel. So if you want to implement a strict one-to-one application, you need to add some additional logic to your application codes.

> If someone has joined your target channel, you will receive a `user-joined` event immediately after joining successfully. 

Here is my suggestion:
- call `client.join` to join the target channel and wait for 1s after joining successfully.
- if you received `user-joined` twice in 1s, call `client.leave` and show a toast to your user.
