### ISSUE TITLE
Client.join timeout on Microsoft Edge 44.19041.1.0

### ISSUE THREAD

**Issue by mannu598** [AgoraIO-Community/AgoraWebSDK-NG#14]
Hi,

I am trying to use NG SDK and facing issue on Microsoft Edge.

I am not able to connect and connection always fails with a timeout. I can see the same issue with the NG SDK Demo located at https://agoraio-community.github.io/AgoraWebSDK-NG/demo/basicVideoCall/index.html

Is Edge supported in new SDK and future plans or is there a workaround available to fix this? 

I am using AgoraRTC.checkSystemRequirements() to find out compatibility and I am getting "true" from this method on the Edge browser.

Below is the console log from https://agoraio-community.github.io/AgoraWebSDK-NG/demo/basicVideoCall/index.html
**------------------------------------------------------------------------------------**
HTML1300: Navigation occurred.
index.html (1,1)

00:00:56:676 Agora-SDK [INFO]: browser compatibility [object Object] [object Object]

00:01:24:586 Agora-SDK [INFO]: [c5f53] Initializing AgoraRTC client v0.1.9, mode: rtc, codec: h264
AgoraRTC_N.js (5,143243)

00:01:24:586 Agora-SDK [DEBUG]: [c5f53] connection state change: DISCONNECTED -> CONNECTING
AgoraRTC_N.js (5,143243)

00:01:24:587 Agora-SDK [DEBUG]: Flush cached event reporting: 1
AgoraRTC_N.js (5,143243)

00:01:24:588 Agora-SDK [DEBUG]: [c5f53] Connect to choose_server: https://webrtc2-ap-web-1.agora.io/api/v1
AgoraRTC_N.js (5,143243)

00:01:24:589 Agora-SDK [DEBUG]: [c5f53] Connect to choose_server: https://webrtc2-ap-web-2.agoraio.cn/api/v1
AgoraRTC_N.js (5,143243)

00:01:24:590 Agora-SDK [DEBUG]: GetUserMedia {"audio":{}}
AgoraRTC_N.js (5,143243)

00:01:24:592 Agora-SDK [DEBUG]: GetUserMedia {"video":{}}
AgoraRTC_N.js (5,143243)

WEBAUDIO17060: The given destination is not connected.
AgoraRTC_N.js (5,189655)

00:01:26:303 Agora-SDK [DEBUG]: start check mediaStreamTrack resolution [object MediaStreamTrack]

00:01:26:350 Agora-SDK [DEBUG]: [c5f53] Connect to choose_server: https://webrtc2-ap-web-3.agora.io/api/v1
AgoraRTC_N.js (5,143243)

00:01:26:350 Agora-SDK [DEBUG]: [c5f53] Connect to choose_server: https://webrtc2-ap-web-4.agoraio.cn/api/v1
AgoraRTC_N.js (5,143243)

00:01:26:524 Agora-SDK [DEBUG]: get track resolution: 640 x 360 [object MediaStreamTrack]

**00:02:24:598 Agora-SDK [DEBUG]: Client.join timeout**

**Comment by disoul** [comment]
Microsoft Edge 44 is not supported in this SDK, we will update `checkSystemRequirements ` result.

If you want to use Microsoft  Edge, please update your Edge to v80+.

**Comment by mannu598** [comment]
Thanks @disoul for the quick reply.
