### ISSUE TITLE
Interoperability issue with native sdk

### ISSUE THREAD

**Issue by albert-kov** [AgoraIO-Community/AgoraWebSDK-NG#17]
Hey,

Trying to integrate `agora-rtc-sdk-ng 0.1.9`  and have issues with `AgoraRtcEngine_iOS 3.0.1` for ios, while video from web appears on ios device as and sound, web sdk cannot subscribe to video from ios device, therefore no video from ios on the web and no sound from the web, for native rtc engine this is enabled `agoraKit?.enableWebSdkInteroperability(true)` 
video sharing works between ios devices but seems to have issues between native and web.

Was testing it on chrome Version 83.0.4103.61 (Official Build) (64-bit) macos
Iphone X 13.3.1

Could you please give a tip what could be wrong,
Thanks in advance!

**Comment by disoul** [comment]
Sorry I can not reproduce this issue. It works fine in my Chrome and iPhone.

Have you tried to use our [demo page](https://agoraio-community.github.io/AgoraWebSDK-NG/demo/basicVideoCall/index.html)? If it is still not working, please [enableLogUpload](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#enablelogupload)  and give me your `appid`, `uid` and `channel name` info, I will check the logs and try to find what's wrong with your application.

**Comment by albert-kov** [comment]
So it works for you with the native app? From this https://docs.agora.io/en/faq/web_on_mobile I understood it only supports receiving streams, but not publishing? That what I am experiencing right now, I have debug mode of web sdk and it not shows that web sdk subscribed to native app client, but I can see video and hear voice on mobile app

**Comment by disoul** [comment]
This https://docs.agora.io/en/faq/web_on_mobile case is using websdk on a mobile browser(mobile chrome/safari or webview). I think your problem is using websdk with your native app which is using agora native sdk.

This case was fully tested, you can try to use our [demo page](https://agoraio-community.github.io/AgoraWebSDK-NG/demo/basicVideoCall/index.html) with your native app(just enter the same appid and channel).

**Comment by albert-kov** [comment]
Thanks, the issue is on my side.

**Comment by albert-kov** [comment]
hey, @disoul

I was looking into this one: https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/?_ga=2.56873507.863354283.1592325729-2104085712.1592325729 this works I get video and audio from mobile app, but I couldn't make it work with this [demo page](https://agoraio-community.github.io/AgoraWebSDK-NG/demo/basicVideoCall/index.html) which uses newer sdk, I enabled log upload, could you take a look, please, and tell what might be wrong, 

appId: `a1887e2d370f4365b911fe125e670a14`
channel name: `call_21f9b461-8dfe-41ac-8cb7-af699bfd19ca`
uid: `4585144`

**Comment by disoul** [comment]
I think your issue is caused by using `String UID` which is not you expected. You passed a `"4585144"` as the UID  param to `client.join`. You should pass an int value to it.

**Comment by albert-kov** [comment]
thanks, that was an issue
