### ISSUE TITLE
API 文档缺少关于`Interface IElectronNativeImage`的介绍

### ISSUE THREAD

**Issue by chudongvip** [AgoraIO-Community/AgoraWebSDK-NG#2]
https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/electrondesktopcapturersource.html

**Comment by disoul** [comment]
https://www.electronjs.org/docs/api/native-image#class-nativeimage

**Comment by chudongvip** [comment]
我的意思是链接不过去，看不多里面具体有哪些属性
![image](https://user-images.githubusercontent.com/31001856/76294517-f24b1700-62ed-11ea-946e-f60c05d0f712.png)

**Comment by disoul** [comment]
这个文档是 typedoc  生成的，不支持在这个位置跳转到外部的链接，所以在下面的描述里加的链接

**Comment by chudongvip** [comment]
好的，十分感谢！新的SDK看起来很不错，加油！
----
你刚说你们用的是TypeDoc写的，我看了一下 TypeDoc 官网的API文档，我想知道这个`Defined in xxxxxx/xxx.ts`怎么隐藏掉，在他们的官网里没有找到关于隐藏的这个属性，感恩！
![image](https://user-images.githubusercontent.com/31001856/76297057-27f1ff00-62f2-11ea-8e68-234bfa25a7a5.png)

**Comment by disoul** [comment]
感谢你的支持

我们是通过自己定制 [TypeDoc Theme](https://typedoc.org/guides/themes/) 来实现的，修改默认 theme 的 [hbs 模版文件](https://handlebarsjs.com/)

**Comment by chudongvip** [comment]
明白了，十分感谢！请问NG 什么时候才能上线？

**Comment by disoul** [comment]
现在你可以认为 NG 已经上线，我们也会推荐新客户去使用，有问题我们也会第一时间修复，有功能会第一时间更新，优先级和官网版本没有太多区别。

但是在官网上进行大规模的不兼容更新是一个很难的事情，需要我们进行多轮的客户验证和使用反馈，目前没有确切上官网的时间计划

**Comment by jinyeqing** [comment]
> 明白了，十分感谢！请问NG 什么时候才能上线？

@chudongvip  我们下周准备组织一个交流活动，定向邀请开发者来参与体验，然后根据咱们的反馈进行更多的功能和体验完善。后续大家有NG版本问题也可以及时交流，你如果愿意参与可以发你的微信回复给我邮箱： jinyeqing@agora.io
