### ISSUE TITLE
screenshare popup failed to open in poor network

### ISSUE THREAD

**Issue by livefire2015** [AgoraIO-Community/AgoraWebSDK-NG#20]
* Device: MacOS 10.15.5
* Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)
* SDK-NG: 0.1.9
* Problem:
1. Start a basic video call
2. Change Network to poor condition, say, 2G (uplink 10kb/s, downlink 10kb/s, 500 ms latency)
3. Click "Start Screenshare" button
4. Expected: a popup window opens to choose which screen to share
    Actual: no popup window
5. Change Network back to default (wifi)
6. The popup window immediately appears

* Console log during step 4: 
![image](https://user-images.githubusercontent.com/11730364/85171011-138f9d80-b223-11ea-9dcc-bda2392bbe6b.png)

* Question: why does the screenshare popup get stuck somewhere and fail to show up when the network is slow?

**Comment by disoul** [comment]
It seems like that you called `client.join` in your "Start Screenshare" button onclick callback. I think it's not an issue for SDK, `createScreenVideoTrack` does not contain any network logic.
