### ISSUE TITLE
Sample on ReactJS + TypeScript

### ISSUE THREAD

**Issue by sowsan** [AgoraIO-Community/AgoraWebSDK-NG#22]
Is there a sample/documentation on how to use this SDK with ReactJS + TypeScript?

**Comment by disoul** [comment]
Sorry, there is no sample demo with ReactJS and Agora-Web-SDK-NG now. But I think this is a good suggestion, we will add it in next week.

**Comment by sowsan** [comment]
Thanks, it will be great have updated version of this with NG SDK https://github.com/AgoraIO-Community/OpenAgoraWeb-React
