### ISSUE TITLE
How to implement stopScreenSharing event, migrating from regular Web SDK

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#24]
Hi,

With the regular web sdk, i listened for cancel screen share events as follows:
```typescript

      screenSharingStream.on('stopScreenSharing', evt => {
        this._eventBus.emit('stopScreenSharing', evt);
      });
```

How do I replicate this behavior with agora-web-sdk-ng?

Thank you!

**Comment by disoul** [comment]
You can use this event ["track-ended"](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/ilocaltrack.html#event_track_ended).

**Comment by vvedharaju** [comment]
ohh great, didn't notice that event. thank you so much :)
