### ISSUE TITLE
Publish useAgora package to npm .

### ISSUE THREAD

**Issue by matamatanot** [AgoraIO-Community/AgoraWebSDK-NG#28]
Thank for Sharing New React Demo! 
That's exactly NG! There are Functional Components and React Hooks. 

If possible, Please consider publishing `useAgora` hooks to npm package.
To establish both operability and reusability.

**Comment by disoul** [comment]
Yeah, we are working on it. But this `useAgora` API is just an MVP implementation, we will add more convenient functions in the future, such as screen sharing, audio mixing, quality callback, etc.

**Comment by FarazPatankar** [comment]
@disoul any update on the same?

If not an npm package, could you maybe update the React demo here in the repo?
