### ISSUE TITLE
How to handle multiple tracks

### ISSUE THREAD

**Issue by albert-kov** [AgoraIO-Community/AgoraWebSDK-NG#29]
Hey,

I have a use case where I need to play an audio track created from `createMicrophoneAudioTrack` and also would like to have another track playing simultaneously created with  `createBufferSourceAudioTrack` is this possible to have those two audio tracks to publish and play simultaneously? If not what would you suggest for implementing such a use case?

Thanks in advance

**Comment by disoul** [comment]
Have you read this [article](https://agoraio-community.github.io/AgoraWebSDK-NG/docs/en/audio_effect_mixing) about audio mixing?

If you want to play multiple tracks in local, just call `play()` for each `LocalTrack` object. If you want to publish multiple audio tracks, just call `client.publish()` and pass each `LocalAudioTrack` object to its params.

```js
const audioFileTrack = await AgoraRTC.createBufferSourceAudioTrack({
  source: "https://web-demos-static.agora.io/agora/smlt.flac",
});
const microphoneTrack = await AgoraRTC.createMicrophoneAudioTrack();

// start buffer source audio track's audio processing
audioFileTrack.startProcessAudioBuffer();

// play 2 audio tracks
audioFileTrack.play();
microphoneTrack.play();

// publish 2 audio tracks
await client.publish([audioFileTrack, microphoneTrack]);
```

> If you publish multiple audio tracks, SDK will mix multiple audio tracks to one track and send it to Agora's SD-RTN, so the remote user will only receive one audio track.

**Comment by albert-kov** [comment]
Thanks for quick reply, I want remote user to have a control over each track’s volume, so will try implement it creating two clients instead, thanks for your help!
