### ISSUE TITLE
createCustomVideoTrack with audio

### ISSUE THREAD

**Issue by porterde** [AgoraIO-Community/AgoraWebSDK-NG#30]
Calling createCustomVideoTrack with `true` for withAudio returns a list with two tracks (audio and video) if the user selects to share a browser tab and ticks Share Audio, otherwise fails.

It would be helpful if, instead, createCustomVideoTrack with `true` for withAudio returned a list containing only the video track rather than an error if user does not tick Share Audio. Then the app could decide if it would like to request audio, but can gracefully fall back to video only for screen share if user does not agree to share audio.

**Comment by disoul** [comment]
This feature is already supported in the next version and it will be released next week.

**Comment by porterde** [comment]
Awesome, and thanks for the quick reply!

Is there somewhere I can see a roadmap of future releases I could check before asking similar questions?

**Comment by disoul** [comment]
Sorry, the roadmap of this SDK is the internal information, I can not share it on Github.

If you have any feature requirements about this SDK, feel free to post issues to let us know.

> By the way, I think your mean `createScreenVideoTrack` right? Your issue title is `createCustomVideoTrack`.

**Comment by porterde** [comment]
Ok no problem re roadmap. Yes sorry I meant `createScreenVideoTrack`.

**Comment by disoul** [comment]
`v4.0.0` has been released, [createScreenVideoTrack](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#createscreenvideotrack) now support `"auto"` mode.

**Comment by porterde** [comment]
Awesome, thanks!
