### ISSUE TITLE
Frequent issue of no sound or black video screen

### ISSUE THREAD

**Issue by ericluwj** [AgoraIO-Community/AgoraWebSDK-NG#33]
I am using Agora client settings for interactive video broadcasting:
```
{ mode: "live", codec: "vp8" }
```

And to reduce bandwidth usage, I am using the following camera encoder profile:
```
{ encoderConfig: "180p_1" }
```

My users are frequently complaining of no sound or black video screen.

I am using your demo Agora React hook code.

Is the Agora client so unstable such that sometimes the published user does not get registered on the playback side?
What is the recommended way to ensure that the playback client can always consistently receive both published video and audio?

**Comment by disoul** [comment]
This experience is unexpected, I think there are maybe some issues in Agora Service itself. Can you provide more info?

You can call `AgoraRTC.enableLogUpload()` to enable the log uploading and try to reproduce this issue again. We need the `ChannelName` and `UID` to locate the service logs.

**Comment by vvedharaju** [comment]
is there any update on this? I am noticing this as well.
