### ISSUE TITLE
NPM repository is broken

### ISSUE THREAD

**Issue by porterde** [AgoraIO-Community/AgoraWebSDK-NG#34]
https://www.npmjs.com/package/agora-rtc-sdk-ng shows version v4.0.1 (which is not a tag in this repo) and attempt to download v4.0.0 which worked last week now fails.

**Comment by disoul** [comment]
I am sorry, this is my mistake. The `4.0.0` version in npm has some unstable codes which can't be published. The npm does not support replace the same version so I released 4.0.1 instead. 

I will update this repo to 4.0.1 in tomorrow.

**Comment by porterde** [comment]
Thanks, I'll test tomorrow.

This broke our build. In the future `deprecate` would be a better option than `unpublish` :)

**Comment by disoul** [comment]
@porterde yeah, you are tight
