### ISSUE TITLE
setEnabled on videoStream is sometimes not publishing the video stream [4.0.1] 

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#35]
In 4.0.1, I noticed this happening frequently in rtc mode. So far, it has not happened to us in live broadcast mode. Please help!

**Comment by vvedharaju** [comment]
Oh, the issue is if call setEnabled(false) on a localTrack before publishing both the tracks. Whichever track I call setEnabled(false) on before publishing is not published when I later call setEnabled(true). Is that expected behavior? Do I need to explicitly publish the track again when I later call setEnabled(true)?

**Comment by disoul** [comment]
You can not publish a disabled track, but you can disable a published track.

- create-track -> disable-track -> publish (will throw TRACK_IS_DISABLED error!)
- create-track -> publish -> disable-track -> enable-track (this is ok)
- create-track -> disable-track -> enable-track -> publish -> disable-track -> enable-track (this is ok too)

**Comment by vvedharaju** [comment]
got it 👍 just checking client.localTracks and publishing if its not already published
