### ISSUE TITLE
How to know that the local video/audio track is not enabled?

### ISSUE THREAD

**Issue by albusphan** [AgoraIO-Community/AgoraWebSDK-NG#36]
Hi, so in our web app there an option to toggle on and off the local video.

Could you tell me how to get the current state of the local track (I need that for display placeholder/user avatar)
I tried out the localTrack.isPlaying but it doesn't seem work.

Thank you

**Comment by disoul** [comment]
you can use this private property:`LocalTrack._enabled`. We will make this property public in the next version.

**Comment by albusphan** [comment]
Thank you for quick support @disoul
