### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#37]
I just wanted to double check that this library is production ready. We have an event on Monday with 500 people where we will be using our app migrated to this new ng library

**Comment by vvedharaju** [comment]
We will have a lot of people joining from safar on an ipad

**Comment by disoul** [comment]
This SDK is production-ready on desktop. But we don't have a full test with mobile browsers.

**Comment by FarazPatankar** [comment]
Is there an update on this, @disoul? We're on the old SDK and it is really cumbersome whenever we want to make changes to the implementation. Also, a promise-based approach + TS is very important to us.

Has this SDK been tested on mobile browsers now? Also, when you say desktop, has that been fully tested?

**Comment by ashishdgohil** [comment]
Hi, is the SDK production-ready on desktop & mobile browsers? as we need to make the use of it in our app which Is new.
