### ISSUE TITLE
Echo issue and failed to close media track.

### ISSUE THREAD

**Issue by skywalkershen** [AgoraIO-Community/AgoraWebSDK-NG#4]
Hi, i‘m having problem with the following issues and wish you can help me and shed some light upon them:
1. I'm getting loud echos and noises when duplicating pages to test. 
While checking your demo page, I found there is no noice or echo at all, yet I failed figure out the difference between our ways to use audiotrack.

in your demo, you are just using 
`localTracks.audioTrack = AgoraRTC.createMicrophoneAudioTrack() to create audiotrack. `
I'm using the same way to create audio track and have tried using audio config to cancel noise and echo, but that doesn't work.
`rtc.localAudioTrack = await AgoraRTC.createMicrophoneAudioTrack({AEC: true, ANS: true, AGC: true});
`
And after the audio track gets created, I'm only publishing it, and not playing it at local, so the audioTrack.play() only gets called in the `user-publish` event handler.

2. I'm having trouble close the track and releasing the device bound to it.
`await rtc.client.unpublish();
   rtc.localVideoTrack.stop();
   rtc.localAudioTrack.stop();
   rtc.localVideoTrack.close();
   rtc.localAudioTrack.close();`
Yet the media play stopped while the devices are still in use.

Could you please give me some advice upon these issues? Thank you.

**Comment by jinyeqing** [comment]
I wonder if you are come from china , if you are , We are going to organize an exchange activity, invite developers to participate, and then make more functions and experience improvement according to our feedback.  If you are willing to participate, you can send your wechat reply to my email：jinyeqing@agora.io

**Comment by skywalkershen** [comment]
好的，另外，可否麻烦帮忙看下我提的问题？多谢

**Comment by disoul** [comment]
To be honest, I'm confused about your questions.

For question 1, testing the one-to-one call on the same device definitely caused echo issues (except using headphones). If you want to test, try to use two devices or using headphones.

> The echo issue occurs because the microphone records the audio wave of the speakers. 

For question 2, call `LocalTrack.close` will release the media device. You can try it in our demo (just click the Leave button on the page). I guess in your case it might be another web page or application that is using the camera or microphone.

If you confirm that is a bug, please give me your sample codes and I will try to reproduce.

Thank you!

**Comment by msi008** [comment]
@skywalkershen  应该是你本地没有mute导致的，现在只要本地不播放音频即可，另外降噪配置默认是开启的吧

**Comment by disoul** [comment]
@skywalkershen
