### ISSUE TITLE
Chrome v74+ screenshare of browser tab with audio should be supported on Mac OS

### ISSUE THREAD

**Issue by porterde** [AgoraIO-Community/AgoraWebSDK-NG#40]
Mac OS 10.15, Chrome v83, AgoraWebSDK-NG v4.0.1.

Using `createScreenVideoTrack` with `withAudio` set to `auto` does not show the Share Audio checkbox in the Chrome dialog to select a tab.

With `withAudio` set to `enable` an error occurs: Agora-SDK [ERROR]: AgoraRTCError NOT_SUPPORT: your browser or platform is not support share-screen with audio

However, on the same Mac OS and Chrome versions, Google Meet web app shows the Share Audio checkbox and is able to share audio stream from selected tab. MDN browser compatibility also indicates Chrome v74+ on Mac OS should be able to share audio from a tab. https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#Browser_compatibility

**Comment by disoul** [comment]
Thanks for your feedback. We will add MacOS chrome tab support in the next version.

**Comment by albusphan** [comment]
hi @disoul , is there any walkaround to share screen for this version ?

**Comment by disoul** [comment]
@albusphan 
you can call `getDisplayMedia` by yourself and pass your `MediaStreamTrack` objects to [createCustomVideoTrack](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#createcustomvideotrack) and [createCustomAudioTrack](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#createcustomaudiotrack)

**Comment by porterde** [comment]
Appears to be fixed in 4.1.0 thanks
