### ISSUE TITLE
Getting error AgoraRTCError INVALID_PARAMS

### ISSUE THREAD

**Issue by smartnav** [AgoraIO-Community/AgoraWebSDK-NG#41]
Whenever I am trying to subscribe the client then this error is coming, previously this was working perfect. It spoiled my demo.

**message: "AgoraRTCError INVALID_PARAMS: mediaType can only be set as [\"audio\",\"video\"]"**

**Comment by vvedharaju** [comment]
try passing the mediaType when you're subscribing to the user `this._client.subscribe(user, mediaType).` I had this same issue when upgrading to 4.0.0.

**Comment by disoul** [comment]
Demo codes have been updated.
