### ISSUE TITLE
2-5 second delay after unmuting with setEnabled

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#43]
When I unmute a user using setEnabled(true) on the audioTrack, it's taking a long time before audio is sent to the other users. The initial few words are never even published.

**Comment by disoul** [comment]
Confirmed. We will resolve this bad experience as soon as possible.

**Comment by vvedharaju** [comment]
@disoul sounds good. any idea how long that will take?

**Comment by disoul** [comment]
This issue has been fixed in Agora WebRTC Gateway And it will be released in Aug.

There are no changes in SDK codes, but we have to wait for the gray release to complete.

**Comment by abdullah** [comment]
@disoul 👋  Hi. I'm subscribing to this issue. Can you comment when releasing completed or share a link that can be followed?

**Comment by utsavtiwary04** [comment]
Following this issue. Would be great if you can hint at a date of the next release of NG sdk. Thanks @disoul !

**Comment by disoul** [comment]
Hi guys, the next version will be released around Aug 20th.

**Comment by vvedharaju** [comment]
@disoul has this been released?

**Comment by disoul** [comment]
fixed in v4.1.0
