### ISSUE TITLE
ERR_PUBLISH_REQUEST_INVALID: publish low stream before high data

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#44]
Got this error and streams went blank for a bit before connecting back

**Comment by disoul** [comment]
Can you provide a complete log file or enable the log upload?

> If you enabled the log upload, just tell me the `uid` and `channel` so I can find logs in our log server.

**Comment by vvedharaju** [comment]
Log upload is enabled, what info should I share with you

**Comment by disoul** [comment]
> Log upload is enabled, what info should I share with you

`channel name` and `uid` where the problem occurred

**Comment by vvedharaju** [comment]
I don't remember which uid exactly. But it's one of these:

channel name: STAGING215, uid: 451
channel name: STAGING215, uid: 453

Thank you

**Comment by disoul** [comment]
fixed in v4.1.0
