### ISSUE TITLE
On iPad Safari audio track published with setEnabled(true) is not playing video even after user interaction

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#45]
Works fine for chrome

**Comment by disoul** [comment]
Is your iPad Safari address bar has this icon when this issue occurred?
![image](https://user-images.githubusercontent.com/8756894/88359481-56560f80-cda5-11ea-8292-ca358ceee5e0.png)

> Seems like camera and microphone have been disabled by IOS Safari in this case.

You can try not to call `AgoraRTC.getDevices` before calling `createMicrophoneAudioTrack/createCameraVideoTrack` to avoid this problem.

**Comment by vvedharaju** [comment]
This is an issue from the audience end in live broadcast mode. There was one audience member on iOS safari and one on Chrome. The audio played fine for the chrome user but not safari after setEnabled(false) and then setEnabled (true). The audio is playing for newly published streams however

**Comment by disoul** [comment]
> This is an issue from the audience end in live broadcast mode. There was one audience member on iOS safari and one on Chrome. The audio played fine for the chrome user but not safari after setEnabled(false) and then setEnabled (true). The audio is playing for newly published streams however

I have reproduced this issue on my iPad. We will try to fix it in the next version.

**Comment by vvedharaju** [comment]
Great! Will make sure to add steps next time 👍

**Comment by vvedharaju** [comment]
@disoul will this fix be included in the next version?

**Comment by albusphan** [comment]
hi @disoul , @vvedharaju  do you guys have any walkaround for this issue?

**Comment by albusphan** [comment]
FYI, just test on Safari version 14 and it work fine, so maybe the issue is not relate to agora?
cc @disoul , @vvedharaju , @HAHAHA44

**Comment by HAHAHA44** [comment]
Solved in 4.1.0
