### ISSUE TITLE
Massive echo in the audio just throughout the call

### ISSUE THREAD

**Issue by utsavtiwary04** [AgoraIO-Community/AgoraWebSDK-NG#48]
### Describe the bug
As soon as I join the channel and create createMicrophoneAudioTrack, there is a massive echo issue and that makes it impossible to continue the call. This is happening consistently on Mac + Chrome with just one user in the channel. No other video calling website or software is open at the same time.

**Channel**:  C88-L5af1  

**UID**:    101

Platform and Browser: Macbook + Google Chrome 84.0.4147.89 (Official Build) 

SDK Version:   Agora NG 4.0.1

**Comment by disoul** [comment]
I notice that you called `LocalAudioTrack.play`. This is the echo issue's root cause.

> The microphone will record the audio wave of the speaker If you are not using headphone. And this will cause the echo issue.

**Comment by utsavtiwary04** [comment]
Resolved !
