### ISSUE TITLE
DOM related performance issue

### ISSUE THREAD

**Issue by abdullah** [AgoraIO-Community/AgoraWebSDK-NG#49]
### Describe the bug
When you call the `setEnabled(true)`helper of `localVideoTrack` the SDK attaches additional `video` and `canvas` element to the dom. For example, if you enabled the `dualStreamMode` and call the `setEnabled` function more than once you will see the `nx2` elements in the document.

Platform and Browser:    
-- Browsers that support the `dualStreamMode`

SDK Version:    
4.0.1

### To Reproduce

1. Enable dual-stream mode and Publish a new video track
2. Toggle the video by calling the `setEnabled` function more than once
3. Open the developer console scroll to the bottom
4. You will see `nx2` video/canvas elements

### Additional context
To improve the performance if you have a chance to use the [`offscreencanvas`](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) it might be better than `canvas` API 👋 

Also, Can you have a guide to improve the device CPU and Memory usage?

**Comment by disoul** [comment]
Thanks for your reporting, this issue has been fixed in our develop branch. This fix is included in the next version and will be released next month.

You are right, `offscreencanvas` is a better choice, we will switch to this api in the future. Thanks again!

**Comment by FarazPatankar** [comment]
Hey @disoul, is there an update on this and any timeline for when the new release comes out?

**Comment by disoul** [comment]
fixed in v4.1.0
