### ISSUE TITLE
Q: Cloud-recording layout 

### ISSUE THREAD

**Issue by abdullah** [AgoraIO-Community/AgoraWebSDK-NG#51]
Hi, 👋  We are trying to record the channel using `cloud-recording`. We plan to record the channel using a custom layout that places the active-speaker center of the canvas, custom thumbnail size, watermark, etc.  Other layout types do not fit with we want. 

We have read the entire documentation including RTMP-Converter, Cloud-recording, On-premise recording. We want to know who is joined the channel, who is speaking, who has disabled the camera etc. on the backend side since giving this responsibility to the client (WEB) is not reliable because of the connection issues, bad network connection, etc. When we try to give this privilege to someone on the channel and when this client disconnects, our layout will not be updated (still recording) or we have to assign this role, someone, on the channel again. This is not meaningful IMHO. 

We've found something on the [on-premise recording ](https://github.com/AgoraIO/Basic-Recording/tree/master/On-Premise-Recording-Nodejs). If we use on-premise recording we can get the client events on the backend-side (node).

Here is the question; How can we listen to the channel events that we want to record on BE side? Is there a webhook or SDK for it without using the on-premise recording product? 

I think this issue should not be here but I don't know where I should post it.

**Comment by plutoless** [comment]
hi @abdullah , you may use cloud-recording to achieve what you want. we have a set of webhook apis which you will receive once you start using cloud recording. the stream status can be obtained via 43 and 44.
However cloud-recording is not providing mute status notification, we have plans to extend cloud recording webhook apis but these are still in experiment period. For the moment if you want to customize the layout based on mute status you will have to maintain it yourself on your own server.

**Comment by abdullah** [comment]
@plutoless Thanks for your comment. I'm closing it. ❤️
