### ISSUE TITLE
The play request was interrupted by a call to pause

### ISSUE THREAD

**Issue by utsavtiwary04** [AgoraIO-Community/AgoraWebSDK-NG#52]
### Describe the bug
Unable to stream a remote user's track.

### SDK Logs
> You should call [enableLogUpload](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#enablelogupload) to enable log upload to Agora's Log Server.

**Channel**: C662-La1f7    

**UID**: 1140

Platform and Browser:  Agora Web SDK NG, Chrome

SDK Version:    

### To Reproduce
Scenario - 4 people were hosts in live mode.
One person refreshed his screen and joined back.
He was only able to play one stream and the other streams threw an error saying **The play request was interrupted by a call to pause**

![WhatsApp Image 2020-08-02 at 15 49 48](https://user-images.githubusercontent.com/6642834/89121887-9e311100-d4e0-11ea-80f8-16cfa7264ff6.jpeg)

**Comment by disoul** [comment]
You can ignore this warning, the SDK will auto resume all video element in a `setInterval`. Some of these auto-resume operations will cause this warning, but it does not effect your application.

**Comment by utsavtiwary04** [comment]
Also as a small followup question around react and on("stream-published") event .. can you help ?

**Comment by utsavtiwary04** [comment]
Resolved
