### ISSUE TITLE
Chrome Version 85 beta issue

### ISSUE THREAD

**Issue by dentesting** [AgoraIO-Community/AgoraWebSDK-NG#53]
Hi,

Its not really a bug yet, but it may well be soon if not monitored. We are using Chrome Version 85.0.4183.48 (Official Build) **beta** (64-bit) to be future proof and make sure our apps are working on coming browser releases from day one.
In this Chrome Version 85 the WebSDK NG (and also previous SDK) creates multiple connections, which leads to Firewall blocking all network traffic with error  `Maximum sessions per host (1000) was exceeded` after about 20 seconds. It also makes API reconnects all the time during a call and leads to many records in Agora Analysts for one call.

It works fine on Official Build Version 84.0.4147.105 (Official Build) (64-bit).

Thanks.

**Comment by disoul** [comment]
Thanks for your report, we are tracking this issue. We will resolve this issue before the next stable version of Chrome released.

**Comment by dentesting** [comment]
Great stuff, thanks!

**Comment by disoul** [comment]
This issue has been fixed on the server-side, closed.
