### ISSUE TITLE
Safari Crashes on streaming

### ISSUE THREAD

**Issue by utsavtiwary04** [AgoraIO-Community/AgoraWebSDK-NG#54]
### Describe the bug
When a user joined streaming from safari, the entire browser froze.

### SDK Logs
> You should call [enableLogUpload](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#enablelogupload) to enable log upload to Agora's Log Server.

**Channel**:    C671-Lb437

**UID**:   101 (first participant, chrome), 1404 (joins via safari, crash)

Platform and Browser:    

SDK Version:  Agora Web SDK NG  

### To Reproduce
1. Go to chrome and join Channel  and start streaming (live mode, role is host)
2. Go on safari as second user (live mode, role is audience)
3. Change role of 2nd audience to host and start streaming
4. Safari freezes, also causes chrome to freeze a bit

**Comment by utsavtiwary04** [comment]
@disoul one thing we noticed is that on safari, if the resolution is lower than 480, it crashes while using NG. Earlier it wasn't the case. What do you think ?

**Comment by disoul** [comment]
Safari and Firefox cannot capture resolutions below 480p. (In fact, it depends on your camera device. Chrome will auto down-scale the video source to fit the low resolutions but Safari and FF will not). I recommend not to capture low resolutions video in Safari and Firefox.

**Comment by utsavtiwary04** [comment]
Resolved with suggestion
