### ISSUE TITLE
RTCPeerConnection.removeTrack does not implement interface RTCRTPSender

### ISSUE THREAD

**Issue by utsavtiwary04** [AgoraIO-Community/AgoraWebSDK-NG#56]
### Describe the bug
Encountering a certain error while doing setEnabled of localtrack

### SDK Logs
> You should call [enableLogUpload](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#enablelogupload) to enable log upload to Agora's Log Server.

**Channel**:    C655-L5fe1

**UID**:    101

Platform and Browser:    Web, Chrome

SDK Version:    Agora SDK NG

### To Reproduce

Trigger setEnabled(true/false) on a published video/audio track
![WhatsApp Image 2020-08-06 at 01 01 45](https://user-images.githubusercontent.com/6642834/89456255-377e5280-d781-11ea-81b5-4ad955e99223.jpeg)

**Comment by disoul** [comment]
Are you using Chrome's mobile dev tools? This will change your UserAgent and cause this error.

**Comment by utsavtiwary04** [comment]
Understood @disoul . What's the resolution ?

**Comment by disoul** [comment]
Do not use Chrome's mobile dev tools to change your UserAgent to iOS Safari. You should select an Android device to avoid this error. (The default UA for Android device is Chrome).
