### ISSUE TITLE
Pass UID on join using token

### ISSUE THREAD

**Issue by UlliBe** [AgoraIO-Community/AgoraWebSDK-NG#59]
Hi,
Using the AgoraWebSDK-NG with Angular 10, and C# as the backend to create a token.

If i create the token using "0" as the UID (string), i can successfully call client.join .
If i create the tokin using any other value as UID, the token will be rejected.
The rejection happens no matter if its integer or string, or a stringified integer value, and there is no difference if i pass the value as string or number on client.join, or pass null.

Would anyone have a hint where this might originate?

Thank you!

**Comment by disoul** [comment]
Sorry, I have no idea about this. I think this is not a bug for NG SDK, there may be some issues in your C# token service.

**Comment by UlliBe** [comment]
Sorry I bothered, figured it out late at night. My bad for trusting my own input, i found that i used a different hash method for the channel name... Shame on me!
