### ISSUE TITLE
官方demo有报错

### ISSUE THREAD

**Issue by cieldon32** [AgoraIO-Community/AgoraWebSDK-NG#6]
demo地址：https://agoraio-community.github.io/AgoraWebSDK-NG/demo/basicVideoCall/index.html
点击退出时，报错：
![image](https://user-images.githubusercontent.com/18715289/78000112-55b4eb80-7366-11ea-804b-f584ffe35573.png)

顺带问题：
1. 频道名如何获取呢， 只能拿到频道链接

**Comment by disoul** [comment]
这个报错应该是因为你 Join 本身失败导致的（我猜测你可能 token 填错了？），Join 本身失败会导致SDK 将频道状态重新设置成 DISCONNECTED 也就是离开了频道，所以再调用 leave 就会报错操作非法，Demo 为了代码能看起来简单这些容错处理没有加上。

另外，频道号是由你自己指定的，只要是没有特殊字符的字符串就可以。这部分可以参阅 [Agora 平台术语](https://docs.agora.io/cn/Agora%20Platform/terms?platform=All%20Platforms#%E9%A2%91%E9%81%93)
