### ISSUE TITLE
Channe with have more that 17 person with host role

### ISSUE THREAD

**Issue by albusphan** [AgoraIO-Community/AgoraWebSDK-NG#62]
### Describe the bug

Hi agora team, I read on the document that the maximum host is 17, is there any problem if more than 17 joins, what agora do on under the hooks for that case.
And I also use the capture on the agora cloud. is there any problem when more than 17 joins ?

Platform and Browser:   Chrome

SDK Version:    4.0.1

**Comment by disoul** [comment]
If there are more than 17 publishers in the channel, the subscriber will only receive 17 streams randomly.

**Comment by albusphan** [comment]
Thank you @disoul , and how about the capture function on the agora cloud, it will capture all the publishers or random 17?

**Comment by disoul** [comment]
Sorry, I don't know the details about cloud recording, I suggest that you can submit a ticket in the Agora Support (https://agora-ticket.agora.io/)

**Comment by albusphan** [comment]
Thank you for quick response @disoul

**Comment by albusphan** [comment]
hi @disoul, so is there any use case that I can subscribe to all the audio track if more than 17
So sorry for asking a lot of questions.

**Comment by HAHAHA44** [comment]
You can add clients to different channels for more than 17 publishers, and create multiple clients on the receiving side to join multiple channels at the same time to subscribe to all publishers. The user management can be done on your own server.

For example: 
Publisher 1 -> Client 1 -> publish to Channel A
Publisher 2 -> Client 2 -> publish to Channel A
Publisher 3 -> Client 3 -> publish to Channel A
Publisher 4 -> Client 4 -> publish to Channel B
Publisher 5 -> Client 5 -> publish to Channel B
Publisher 6 -> Client 6 -> publish to Channel B

Receiver 1 -> Client 7 -> join Channel A -> receive Publisher 1, 2, 3
                  -> Client 8 -> join Channel B -> receive Publisher 4, 5, 6

**Comment by utsavtiwary04** [comment]
@disoul one extended question - how does the audio call work then ? The docs say it is 10k people at once ?

**Comment by albusphan** [comment]
hi @HAHAHA44, I tried to create multiple clients and join multiple channels in a single browser tab, but it always returns error
UID conflict error. Is there any code sample for the solution that you mention above. Thank you

**Comment by vvedharaju** [comment]
@albusphan were you able to get this working? I have this use case as well

**Comment by HAHAHA44** [comment]
Thanks for feedback, this is a bug of SDK. We will fix it. You can create multiple clients **with different uid** and join multiple channels in a single browser tab to workaround.

**Comment by HAHAHA44** [comment]
Thanks for feedback, this is a  bug of SDK. We will fix it. You can create multiple clients and join multiple channels **with different uid** in a single browser tab to workaround it.

**Comment by albusphan** [comment]
Thank you @HAHAHA44 
FYI @vvedharaju , I have successfully increased the max number of participants to 51 by using 3 different channels.

**Comment by vvedharaju** [comment]
@albusphan have you ben able to support 51 participants without a significant performance impact?

**Comment by albusphan** [comment]
hi @vvedharaju, of course, performance will be affected. but on our product, we only show max 17 videos at a time.

**Comment by albusphan** [comment]
closed
