### ISSUE TITLE
Facebook live streaming

### ISSUE THREAD

**Issue by gibsonsyd** [AgoraIO-Community/AgoraWebSDK-NG#63]
Hi, 

Trying to stream to facebook live using the RTMP feature. 

Followed this guide: [cdn_streaming](https://github.com/AgoraIO-Community/AgoraWebSDK-NG/blob/master/Docs/en/cdn_streaming.md)

RTMP Converter is enabled on my project and I'm using the AgoraWebSDK-NG SDK.

Configured with the suggestions at the bottom of the aforementioned guide: 

Connecting using .join({ mode: 'live', codec: 'h264' })
Setting client role: .setClientRole('host')
Bypassign transcoding as I'm currently only using one (1) broadcaster.
Calling .startLiveStreaming('facebook live url - see below', false)

It seems that the 'Stream Key', required for RTMPS streaming to facebook is not supported? 
I've appended it to the url but still get the same error: **LIVE_STREAMING_CDN_ERROR, code: 30**.

facebook live steaming url: (note replaced sensitive info with xxx)
**rtmps://live-api-s.facebook.com:443/rtmp/**_xxx?s_bl=1&s_ps=1&s_sw=1&s_vt=api-s&a=xxx_

Any suggestions of what I might be doing wrong here?

**Comment by disoul** [comment]
Sorry, raw live streaming does not support the `rtmps` protocol. You should call `client.setLiveTranscoding` and `client.startLiveStreaming('url', true)` to use the trancoding live streaming.

**Comment by gibsonsyd** [comment]
Thank you for the feedback. That works well.
