### ISSUE TITLE
Screen Share on Firefox : device not found error

### ISSUE THREAD

**Issue by utsavtiwary04** [AgoraIO-Community/AgoraWebSDK-NG#65]
### Describe the bug
When I try to screen share on FireFoz browser (Agora SDK NG Web) I get the following error - 

**(AgoraRTCError DEVICE_NOT_FOUND: NotFoundError: The object can not be found here.)**

### SDK Logs
> You should call [enableLogUpload](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartc.html#enablelogupload) to enable log upload to Agora's Log Server.

**Channel**:    C31-L67bd

**UID**:    102

Platform and Browser:   Mozilla Firefox 79.0, Web 

SDK Version:    Agora SDK NG

**Comment by disoul** [comment]
It works fine on my Firefox. I think it is not an error for screen-sharing, it may be caused by your microphone or camera.

**Comment by utsavtiwary04** [comment]
System level permissions were needed for firefox - figured out and fixed !
