### ISSUE TITLE
Joining Multiple Channels w/ same UID

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#67]
Does NG SDK support joining multiple channels with the same UID at the same time. So that I can simultaneously get the audio and video from multiple channels. Looks like this is supported in other sdks but I got an error when trying that here.

https://docs.agora.io/en/Voice/multiple_channel_android

**Comment by HAHAHA44** [comment]
https://github.com/AgoraIO-Community/AgoraWebSDK-NG/issues/62#issuecomment-679914238

**Comment by vvedharaju** [comment]
Great 👍 Also as a followup, when I have multiple client instances, can I do the following:

1. client1 creates an audioTrack and a videoTrack
2. client 1 publishes audioTrack and videoTrack
3. client 1 unpublishes audioTrack and videoTrack
4. client2 publishes audioTrakc and videoTrack that were created by client1

**Comment by vvedharaju** [comment]
Great 👍
