### ISSUE TITLE
Ref for subscibed user

### ISSUE THREAD

**Issue by albusphan** [AgoraIO-Community/AgoraWebSDK-NG#68]
hi Agora team,

Recently, I face this issue when trying to subscribe to a user, seem like the error said that that it subscribes too many times.

AgoraRTCError UNEXPECTED_RESPONSE: ERR_SUBSCRIBE_REQUEST_INVALID: Repeat subscribe request data: {“code”:2021,“data”:{“error_code”:2021,“error_str”:“Repeat subscribe request”}}

is there any walkaround/ indicator to know that the user is already subscribed, or is needed to call the unsubscribe on the 'user-unpublished' event?

**Comment by HAHAHA44** [comment]
Solved in 4.1.0
