### ISSUE TITLE
Documentation Improvement on Audio Call

### ISSUE THREAD

**Issue by utsavtiwary04** [AgoraIO-Community/AgoraWebSDK-NG#69]
Hi @disoul @HAHAHA44 ! Thank you for being ever so helpful

Wanted to understand the following use case (Didn't find it clearly written in Agora Docs) -

Can I have a channel with 8 videos + 100 audios ?

One of the members from the agora team told me on slack that this will work.

My doubt is --
A) this situation will lead to 108 hosts. Is that even possible ?
B) in an audio call with 10,000 participants, every one is host. So that limit of 17 gets broken ? How does it work ?

**Comment by HAHAHA44** [comment]
https://github.com/AgoraIO-Community/AgoraWebSDK-NG/issues/62#issuecomment-674708631

Can this issue resolve your problem?
The 17 limit is a channel limit, you can use multiple clients and multiple channels.

**Comment by utsavtiwary04** [comment]
Actually not -- I'll describe the problem a little more. You are saying that 17 is the channel limit, but based on Agora's  blog this is what I read 

**Q: How many participants does Agora.io audio/video support at the same time in a call?
A: Audio Call: up to 10,000 people speaking at the same time. Video Call: up to 7 people at the same time (Video support for up to 25 people is under development)**


Now when 10,000 people are speaking at the same time, is everyone a host ?

**Comment by HAHAHA44** [comment]
Native app theoretically supports it, but there is still no limit of 17 people. If there are more anchor needs, you can contact customer service.
Web app only supports up to 17 hosts.
