### ISSUE TITLE
Issue joining a channel when using string uid

### ISSUE THREAD

**Issue by aravindm** [AgoraIO-Community/AgoraWebSDK-NG#7]
Hello!

Thanks for writing this library. I am trying to migrate from the Agora web sdk to this library and am unable to join a channel when using a string uid. Below is a snippet of the code that I am using to join the channel:

await videoClient.join(agora_app_id, channel_id, token_obtained_from_the_server, STRING_USER_ID)

The token_obtained_from_server is being generated by my rails application for the string user_id.

Am getting the following error when trying to join the channel:
code: "CAN_NOT_GET_GATEWAY_SERVER"
message: "AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: invalid token, authorized failed"

When I analyzed the xhr requests between using agora sdk and this library, the one difference that I see is, the agora sdk passes the key **detail: {6: STRING_USER_ID}** in the request body for the **/api/v1?action=wrtc_gateway** , whereas this library does not. Not sure if this is what is causing the issue.

Could you please let me know if this library supports string uid and/or if I have to do anything else to get the client.join working?

Thanks!

**Comment by plutoless** [comment]
@disoul

**Comment by disoul** [comment]
@aravindm 
Thanks for your analysis, I have confirmed this bug. I will fix it at v0.1.6 and it will be released today.

I'm sorry I didn't reply to you immediately because I didn't check the email on the weekend.

**Comment by disoul** [comment]
@aravindm
Thanks for your analysis, I have confirmed this bug. it will be fixed in v0.1.6 and will be released today.

I'm sorry I didn't reply to you immediately because I didn't check my email on the weekend.

**Comment by aravindm** [comment]
Have upgraded to v0.1.6 and can confirm that it is working. Thanks!
