### ISSUE TITLE
How to use user-info-updated function in the js code ?

### ISSUE THREAD

**Issue by ashokpal100** [AgoraIO-Community/AgoraWebSDK-NG#70]
Hi,

Please prove the solution of user-info-updated function implementation

user-info-updated(uid: UID, msg: "mute-audio" | "mute-video" | "enable-local-video" | "unmute-audio" | "unmute-video" | "disable-local-video"): void

**Comment by disoul** [comment]
```js
client.on("user-info-updated", (uid, msg) => {
  switch (msg) {
    case "mute-audio":  ...
    case "mute-video":  ... 
  }
});
```

In most cases, you just need `user-published` and `user-unpublished`. This event is only used to receive Agora Native SDK's user info event

**Comment by ashokpal100** [comment]
> ```js
> client.on("user-info-updated", (uid, msg) => {
>   switch (msg) {
>     case "mute-audio":  ...
>     case "mute-video":  ... 
>   }
> });
> ```
> 
> In most cases, you just need `user-published` and `user-unpublished`. This event is only used to receive Agora Native SDK's user info event

thanks for the reply. ok got it
=============== Agora sdk ===============
mute local audio and video just call a 
localStream.muteAudio()
localStream.unmuteAudio()
localStream.unmuteVideo()
localStream.muteVideo() these are works fine

=============== Agora NG sdk=============
but how to mute local audio and video
code below we have used
client = AgoraRTC.createClient({ mode: "rtc", codec: "h264" });
client.on("user-published", handleUserPublished);
client.on("user-unpublished", handleUserUnpublished);
options.uid = await client.join(options.appid, options.channel, options.token || null);
localTracks.audioTrack = await AgoraRTC.createMicrophoneAudioTrack();
localTracks.videoTrack = await AgoraRTC.createCameraVideoTrack()
localTracks.videoTrack.play("local-player");
await client.publish(Object.values(localTracks)) 
above code working fine but not able to achieve mute or unmute local audio and video call

How to mute or unmute local audio and video call ?
Please help

**Comment by disoul** [comment]
you can use  [setEnabled](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/ilocaltrack.html#setenabled)

**Comment by ashokpal100** [comment]
> you can use [setEnabled](https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/ilocaltrack.html#setenabled)

![image](https://user-images.githubusercontent.com/12198089/92101429-bb684080-edfa-11ea-9809-2d929a45ba08.png)

await localTracks.videoTrack.setEnabled(false) ?

**Comment by disoul** [comment]
Are you using v4.0.1 ?

**Comment by ashokpal100** [comment]
> Are you using v4.0.1 ?

Yes
thanks for help im able to do all the things
