### ISSUE TITLE
createMicrophoneAudioTrack timeout

### ISSUE THREAD

**Issue by ashokpal100** [AgoraIO-Community/AgoraWebSDK-NG#73]
Hi Agora Team,

We are using v4.0.1 web agora-ng version.
we are getting createMicrophoneAudioTrack timeout also agora not ask media permission from browser.
Please help. how to fix it

**Comment by HAHAHA44** [comment]
If your browser prohibits audio device access on this page?
Please provide your browser agent, and the specific Agora error message.
