### ISSUE TITLE
Screenshare jumps

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#76]
### Describe the bug
When a screenshare stream is being published by a host for some audience members the screen share experience is not smooth.

1. On every slide change, the slide gets a bit blurry and then looks clear.
2. Sometimes when the slide changes, there's a flash of the previous slide before it stabilizes on the next slide.

We are using the 720p_1 profile for screen share. We are also using optimizationMode: 'detail' for screenshare.

### SDK Logs
Log upload is enabled

SDK Version:    
4.0.1

**Comment by HAHAHA44** [comment]
Sorry for that. We have identified the problem, which is caused by a detail priority related parameter of WebRTC. It will be fixed in the next version.

**Comment by vvedharaju** [comment]
@HAHAHA44 is there anything I can do in the meantime to get a better experience?

**Comment by vvedharaju** [comment]
@HAHAHA44 Also when will the next version be released? Is it possible to have a hotfix version for this since I'm sure this will affect production apps.

**Comment by FarazPatankar** [comment]
Curious about a temporary fix for this as well. Would removing the `optimizationMode` setting help in the meantime? Also, any ETA on the fix?

**Comment by vvedharaju** [comment]
@HAHAHA44 any workaround in the meantime?

**Comment by vvedharaju** [comment]
@HAHAHA44 any update on this?

**Comment by vvedharaju** [comment]
@HAHAHA44 is this resolved?

**Comment by HAHAHA44** [comment]
1. optimizationMode: 'detail' is useful. 
2. **use vp8 codec.**
3. Do not replace a videoTrack to screenShareTrack, there are a bug of chrome that will fix the send bitrate to a low value.

**Comment by vvedharaju** [comment]
@HAHAHA44 issues resolved after switching to vp8 👍 thanks
