### ISSUE TITLE
How to implement local mute / unmute / change volume level?

### ISSUE THREAD

**Issue by fedotxxl** [AgoraIO-Community/AgoraWebSDK-NG#78]
I've found in the release notes that mute was replaced with setEnabled. Looks like `setEnabled ` just destroys the local audio track. Does it mean that I should recreate it and reconnect it?  Can you provide a working example with mute / unmute functionality?

**Comment by HAHAHA44** [comment]
When you call setEnabled(false), the SDK will unpublish the track and destroy it. When you call setEnabled(true), the SDK will create the track and publish it. The only thing you need to do is to listen to the user-published event on the remote end to re-subscribe to this track.
