### ISSUE TITLE
Support for RTMPS in CDN streaming

### ISSUE THREAD

**Issue by becauseinterwebs** [AgoraIO-Community/AgoraWebSDK-NG#79]
Agora SDK 3.2.1 has support for RTMPS streaming to CDN, which is required by Facebook, but SDK NG does not have support for RTMPS (which I found out by upgrading to NG and then was laster confirmed by tech support.) Will RTMPS support be added in the near future?

**Comment by HAHAHA44** [comment]
If the 3.2.1 support for RTMPS streaming to CDN, the Web NG support it too. They use the same push streaming module.

**Comment by becauseinterwebs** [comment]
It has been confirmed by Agora tech support that NG does not support RTMPS.  I have tried unsuccessfully to get it work in NG, although it works fine in 3.2.1.  Hopefully just an oversight and will be added soon.

**Comment by HAHAHA44** [comment]
I can confirm that NG supports this feature. LiveStreaming is implemented on the server side. Regardless of the NG SDK or the old SDK, all they do for live streaming is to send signaling to the server. And the server is the same.
