### ISSUE TITLE
client.on("user-mute-updated") event is not being trigerred.

### ISSUE THREAD

**Issue by CodersGas** [AgoraIO-Community/AgoraWebSDK-NG#80]
```
 rtc.client.on('user-mute-updated', function(event) {
    console.log('################################ MUTE TRIGERRED ##################################', event)
  })
```
I added this event in the `subscribeUser()` method. But when I mute/unmute audio or video, this event is not getting fired. Although I test another event like `'connection-state-change'`, this was getting fired.

Any help would be appreciated.
Thankyou

**Comment by HAHAHA44** [comment]
What sdk version did you use?  We have Removed the APIs about mute and unmute. Now you can use the setEnabled(true/false) to implement your idea.

**Comment by CodersGas** [comment]
Hello. my sdk version is 4.1.0. Could please share a sample line of code or maybe include a sample in the demo of your repo. And, how will I know that the remote user have changed their state of mute/unmute for video or audio to make it realtime?

Thankyou.

**Comment by mjgaylord** [comment]
When a user disables/enables the track, the other users get a publish/unpublish event. You can check if audio/video was muted by a remote host by checking if the audioTrack or videoTrack is undefined after receiving the publish/unpublish event.

**Comment by CodersGas** [comment]
@mjgaylord Thanks for response. I have added the methods to mute and unmute. But when remote user mutes or unmutes the audio/video, I get no log in console. But when I check for local user, I see the log in console. 

Do you know any listener or state that handles the mute/unmute of remote users in the new agora(Agora NG). As, I applied mute-audio and mute-video, but they are deprecated. Then in migration guide I saw its mentioned the event is replaced by user-mute-updated but that also didn't work and won't work as confirmed above by the dev. I am using new Agora(Agora NG) and I am not able to handle this part.

**Comment by mjgaylord** [comment]
@CodersGas there is no listener state for mute/unmute apart from publish/unpublish. When an audio stream is disabled, then the listeners on the other clients will get an unpublish callback and when they unmute they will get a publish callback. You will need to check the audio and video tracks on the user object in these callbacks to tell if the user muted/unmuted those tracks.

**Comment by CodersGas** [comment]
@mjgaylord Alright. I'll check and confirm after trying. 

Thanks a lot for the help to all.

**Comment by CodersGas** [comment]
I have checked and can confirm that the issue is now resolved and this issue can be closed.
Thanks for help 👍
