### ISSUE TITLE
ws request timeout, type: traffic_stats

### ISSUE THREAD

**Issue by utsavtiwary04** [AgoraIO-Community/AgoraWebSDK-NG#81]
### Describe the bug
Getting this error from the user's device that says **"TimeoutError: Request timed out : ws request timeout, type: traffic_stats"**

**Channel**:   C923-Ld4ac
 

**UID**:    101

Platform and Browser:    Chrome, Windows 7

SDK Version:    Web SDK NG

### To Reproduce
No specific steps to reproduce. Consistently seeing this error in console which might be disrupting user experience during a video conferencing call. Can you please help ?

**Comment by utsavtiwary04** [comment]
@disoul @HAHAHA44 Hello people ! Can you please help here ? Many thanks !

**Comment by HAHAHA44** [comment]
This may be because the user's network condition was not good at the time or the user`s network connection is changed, which caused the messages sent by Websocket to time out. This error will not occur when the network is in good condition.

**Comment by utsavtiwary04** [comment]
Understood @HAHAHA44 -- What do you recommend for handling this ? Which event handler would be useful for reconnecting ?

**Comment by HAHAHA44** [comment]
The SDK will automatically reconnect so that you don't need to do anything for reconnect. You can listen the `connection-state-change` event on the client to get the connection state.
