### ISSUE TITLE
AgoraRTCError INVALID_OPERATION: Can't publish stream, no join info!

### ISSUE THREAD

**Issue by utsavtiwary04** [AgoraIO-Community/AgoraWebSDK-NG#82]
### Describe the bug
Getting this error in our logs but are not able to pin point the point of failure or the exact steps to reproduce.

**Channel**: C1154-La912

**UID**: 1888 / 101

Platform and Browser:    Chrome Mac OSX

SDK Version:  Agora Web SDK NG (Latest)

### To Reproduce
Haven't been able to reproduce it consistently yet.

**Comment by HAHAHA44** [comment]
Because you called publish before join.
