### ISSUE TITLE
Question on get int uid from string userAccount

### ISSUE THREAD

**Issue by reotropi** [AgoraIO-Community/AgoraWebSDK-NG#87]
Hi Devs,
I hope you're doing well.

Thank you very much for developing this great SDK. It works very well and solid.

However I have a little question on get int uid from string userAccount,

Right now all of users in my channel is using string uid (including iOS and Android too).
iOS and Android have an API to get their own Int uid after join and we need to save that to DB.

In Web, every uid I found is the string one, even though in iOS and Android they can also get my Int uid.
I have search for the private variable, and I found **client._joinInfo['uid']**. I think it is what I'm searching for.
Can I use that? Will there be something miserable if I do so?

Any help will be very much appreciated 🙇‍♀️ 
Thank you very much for your time.

**Comment by AgentSource** [comment]
We use ```client.uid``` which appears to be the same UID they had in previous versions of the API

Here is a link to the prop https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartcclient.html#uid

One thing to note they have ```UID``` defined as a ```number | string``` so depending on your needs you may need to transform said value. If you take a look at the type definition for ```IAgoraRTCClient``` you can see more details for the client here for that is here => https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/iagorartcclient.html

```
/**
 * The user ID to identify a user in the channel.
 *
 * Each user in the same channel should have a unique user ID with the same data type (number or string).
 */
export declare type UID = number | string;
```

Hope this helps

**Comment by reotropi** [comment]
Hi, @AgentSource 

Thank you very much for your reply.

The client.uid one is returning the string one, which is correct, I also have read the reference you mentioned.

But unfortunately I need the **int** one, even though I'm aware I use the **string** one. 
I checked on `client.isStringUid` value is `true`, so maybe there's a `map` or `private method` to get int uid? (like what value is returned when `client.isStringUid` value is `false`? is it `client._joinInfo['uid']` ? I can just take that value.)

But it is OK if there is nothing like that in the SDK, because question about this case is very low. 🙇 

Thank you once again!

**Comment by HAHAHA44** [comment]
If you had to get the int uid, `client._joinInfo['uid']` is your answer.
