### ISSUE TITLE
DataChannel API?

### ISSUE THREAD

**Issue by ydemartino** [AgoraIO-Community/AgoraWebSDK-NG#89]
Hey, I would like to use the web RTC data channel but I don't see any API to create it and send messages.

**Comment by HAHAHA44** [comment]
We do not have the dataChannel yet, and we will implement  later. If you want to send message to others, please use our RTM production https://docs.agora.io/en/Real-time-Messaging/product_rtm?platform=All%20Platforms.

**Comment by ydemartino** [comment]
Alright, thanks for your answer!
