### ISSUE TITLE
H5 实时直播的支持

### ISSUE THREAD

**Issue by AdamFu** [AgoraIO-Community/AgoraWebSDK-NG#90]
看文档里没有H5 实时直播的说明，是暂时不支持吗？ 如果不支持，后续有支持的时间表吗？
我们目前使用的是旧版的Agora Web SDK，并使用了H5实时直播，需要确定NG的兼容和时间表，谢谢

**Comment by HAHAHA44** [comment]
暂时不支持，还没有后续计划
