### ISSUE TITLE
backgroundImage not working for live streaming to CDN

### ISSUE THREAD

**Issue by vvedharaju** [AgoraIO-Community/AgoraWebSDK-NG#91]
According to the docs we should be able to set a backgroundImage for transcoding when pushing to a CDN. 
https://agoraio-community.github.io/AgoraWebSDK-NG/api/en/interfaces/livestreamingtranscodingconfig.html#backgroundimage

However, this doesn't work. Setting backgroundColor does work. 

Please advise

**Comment by HAHAHA44** [comment]
It is worked in our test. Please confirm your configuration. Maybe the backgroundImage is covered by the videos.
