### ISSUE TITLE
Audio-only streaming doesn't work (no Audio stream or timeout)

### ISSUE THREAD

**Issue by mango009** [AgoraIO-Community/AgoraWebSDK-NG#92]
Couldn't get audio-only streaming to work. Here's my code snippet:
```
  const transCodingConfig = {
    width: 0,
    height: 0,
    audioSampleRate: 48000,
    audioBitrate: 48,
    audioChannels: 1
  };
 await this.agoraClient.setLiveTranscoding(transCodingConfig)
 await this.agoraClient.startLiveStreaming(this.rtmpURL, true);
```
With this code, the startLiveStreaming() call would block until it timeout. Please see the attached log here (
![Screen Shot 2020-10-12 at 10 18 36 PM](https://user-images.githubusercontent.com/2007039/95821649-213fc600-0cdf-11eb-8681-b966490406eb.png)
).

Now if I commented out the width and height attributes in the `transCodingConfig` the call would go through with no error.
```
  const transCodingConfig = {
    //width: 0,
    //height: 0,
    audioSampleRate: 48000,
    audioBitrate: 48,
    audioChannels: 1
  };
```
But there are no audio feed from the RTMP server.
![Screen Shot 2020-10-12 at 10 27 51 PM](https://user-images.githubusercontent.com/2007039/95821821-8d222e80-0cdf-11eb-8cb4-a5d69ed1c9be.png)

This is on the 4.1.0 library.

**Comment by HAHAHA44** [comment]
You have to set the transcodingUsers in transCodingConfig.

**Comment by mango009** [comment]
Thanks for the reply. Since this is an audio-only stream Would the following configuration work?
```
  const transCodingConfig = {
    width: 0,
    height: 0,
    audioSampleRate: 48000,
    audioBitrate: 48,
    audioChannels: 1
    transcodingUsers: {
        alpha: 0,
        audioChannel: 0,
        height: 0,
        uid: "The host UID",
        width: 0,
        x: 0,
        y: 0,
        zOrder: 0
    }
  };
```

**Comment by mango009** [comment]
It works. Thanks.
