### ISSUE TITLE
Provide means to configure class on video-player-track div

### ISSUE THREAD

**Issue by pgib** [AgoraIO-Community/AgoraWebSDK-NG#95]
### Describe the bug

Using the `play()` method on a VideoTrack will inject a `<div>` container inside the HTMLElement that it's provided, but it's hard to style because there's no opportunity to provide a `class` attribute. Can this be added to the `VideoPlayerConfig` so that developers can provide a class name to use with the `<div>` instead of having to create awkward styles to try to target this `<div>`? Perhaps also being able to turn off the injected `style` attributes would be good, too.

![image](https://user-images.githubusercontent.com/13967/96941953-943c0000-1488-11eb-8c5f-e32289f1fa2f.png)

Platform and Browser:   All

SDK Version:    v4.1.0 build: v4.1.0-0-g64d4440(9/4/2020, 5:57:23 PM)

**Comment by HAHAHA44** [comment]
You don`t need to set style for the injected element. You can set the attribute `overflow: hidden` for the container, so that the inner will not overflow the container.

**Comment by HAHAHA44** [comment]
Are there any scenarios where you need to customize the injected elements` style?
